export type BlockType = "ORDER" | "PAYMENT" | "ADDRESS" | "KITCHEN" | "DELIVERY" | "FINISH"

export const BLOCK_TYPE: Record<BlockType, BlockType> = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  ADDRESS: 'ADDRESS',
  KITCHEN: 'KITCHEN',
  DELIVERY: 'DELIVERY',
  FINISH: 'FINISH',
};

export const BLOCKS_ORDERED: BlockType[] = [
  BLOCK_TYPE.ORDER,
  BLOCK_TYPE.PAYMENT,
  BLOCK_TYPE.ADDRESS,
  BLOCK_TYPE.KITCHEN,
  BLOCK_TYPE.DELIVERY,
  BLOCK_TYPE.FINISH,
]